name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_test:
    name: Build & Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pybind11>=2.10 cmake

      - name: Install package & dev deps
        run: pip install -e .[dev]

      - name: CMake configure (Windows only)
        if: runner.os == 'Windows'
        run: cmake -S src/trimcts/cpp -B build -A x64

      - name: Build C++ extension
        run: python setup.py build_ext --inplace

      - name: Run tests with coverage
        run: pytest --cov=src/trimcts --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}    # add this secret in your repo
          files: coverage.xml
          fail_ci_if_error: true
